[package]
name = "test_utils"
version = "0.2.26"
authors = ["Solana Maintainers <maintainers@solana.com>"]
edition = "2018"
publish = false

[dependencies]
libc = "0.2"
solana_rbpf = { path = "../" }
