#ifndef BPF_IR_FUZZERCONFIG_H
#define BPF_IR_FUZZERCONFIG_H

// return value const:
int16_t FAIL_FIRST_REG_UNDER_MIN_BOUND = 1;
int16_t FAIL_FIRST_REG_OVER_UPPER_BOUND = 2;
int16_t FAIL_SECOND_REG_UNDER_MIN_BOUND = 3;
int16_t FAIL_SECOND_REG_OVER_UPPER_BOUND = 4;
int16_t FINISH_RUN = 6;

#endif //BPF_IR_FUZZERCONFIG_H
